services:
  huh.slick.model.config:
    class: HeimrichHannot\SlickBundle\Model\SlickConfigModel
    public: true
  huh.slick.config:
    class: HeimrichHannot\SlickBundle\Config\SlickConfig
    public: true

  HeimrichHannot\SlickBundle\Asset\FrontendAsset:
    autowire: true